apiVersion: v1
kind: Service
metadata:
  name: service-{{ .Values.appName }}
  namespace: {{ .Values.namespace }}
  labels:
{{ toYaml .Values.labels | indent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      {{- if .Values.service.enableNodePort}}
      nodePort: {{ .Values.service.nodePort }}
      {{- end }}
      name: http
  selector:
      service: {{ .Values.podLabels.service | quote }}
